services:
  mysql:
    container_name: mysql
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "dev1234"
      MYSQL_DATABASE: "beer_exchange"
      MYSQL_USER: "beer"
      MYSQL_PASSWORD: "beer1234"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 6033:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  dbdata: