services:
  postgres:
    image: postgres
    container_name: postgres_beer
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: beer
      POSTGRES_PASSWORD: "beer1234"
      POSTGRES_DB: beer_exchange
      PGDATA: /var/lib/postgresql/data
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: beer@beer.com
      PGADMIN_DEFAULT_PASSWORD: beer4321
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  local_pgdata:
  pgadmin-data: